name: Auto-Generate R Plots

on:
  push:
    paths:
      - 'generate_plots.R'
      - 'Songs.csv'
  workflow_dispatch: 

jobs:
  build-plots:
    runs-on: ubuntu-latest
    # 给机器人授予写权限，解决上传报错
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R Environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          # 使用官方预编译二进制包，安装速度会快 10 倍且更稳
          use-public-rspm: true 

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - name: Install R Packages
        run: |
          install.packages(c("tidyverse", "mosaic", "RColorBrewer"), repos="https://packagemanager.posit.co/cran/__linux__/jammy/latest")
        shell: Rscript {0}

      - name: Run R Script
        run: Rscript generate_plots.R

      - name: Commit and Push generated images
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add *.png
          git commit -m "Auto-generated plots by GitHub Actions 🤖" || echo "No changes to commit"
          git push
